### ISSUE TITLE
cool bot

### ISSUE THREAD

**Issue by supmyhava** [rohityadav-sas/Hamster-KeyGen#1]
when and how the bot is generating the keys ?

**Comment by supmyhava** [comment]
root@ger-big:~/Hamster-KeyGen# npm start

> hamster-kombat-key-generator@1.0.0 start
> node src/app.js

(node:1376928) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server running on port 3000
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: chat not found
    at /root/Hamster-KeyGen/node_modules/node-telegram-bot-api/src/telegram.js:316:15
    at tryCatcher (/root/Hamster-KeyGen/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:483:21)

Unhandled rejection Error: ETELEGRAM: 400 Bad Request: chat not found
    at /root/Hamster-KeyGen/node_modules/node-telegram-bot-api/src/telegram.js:316:15
    at tryCatcher (/root/Hamster-KeyGen/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:483:21)

**Comment by rohityadav-sas** [comment]
> when and how the bot is generating the keys ?
> 

You can create your own telegram bot using Botfather.

**Comment by supmyhava** [comment]
> > when and how the bot is generating the keys ?
> 
> You can create your own telegram bot using Botfather.

i did and i send /start to the bot
bot reply
Welcome to the Hamster Key Generator Bot!
and then errors in terminal

**Comment by rohityadav-sas** [comment]
> > > when and how the bot is generating the keys ?
> > 
> > You can create your own telegram bot using Botfather.
> 
> i did and i send /start to the bot
> bot reply
> Welcome to the Hamster Key Generator Bot!
> and then errors in terminal
> 

It says chat not found, You can debug that yourself.

**Comment by supmyhava** [comment]
> > > > when and how the bot is generating the keys ?
> > > 
> > > 
> > > You can create your own telegram bot using Botfather.
> > 
> > 
> > i did and i send /start to the bot
> > bot reply
> > Welcome to the Hamster Key Generator Bot!
> > and then errors in terminal
> 
> It says chat not found, there might be chatId not found issues. You can debug that.

why chat not found i just msg him and he is reply to me :D

**Comment by supmyhava** [comment]
> > > > when and how the bot is generating the keys ?
> > > 
> > > 
> > > You can create your own telegram bot using Botfather.
> > 
> > 
> > i did and i send /start to the bot
> > bot reply
> > Welcome to the Hamster Key Generator Bot!
> > and then errors in terminal
> 
> It says chat not found, You can debug that yourself.

also with another bot:

/start
Welcome to the Hamster Key Generator Bot!

root@ins-1-s8:~/python-telegram-bot/Hamster-KeyGen# npm start

> hamster-kombat-key-generator@1.0.0 start
> node src/app.js

Server running on port 3000
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: chat not found
    at /root/python-telegram-bot/Hamster-KeyGen/node_modules/node-telegram-bot-api/src/telegram.js:316:15
    at tryCatcher (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)

Unhandled rejection Error: ETELEGRAM: 400 Bad Request: chat not found
    at /root/python-telegram-bot/Hamster-KeyGen/node_modules/node-telegram-bot-api/src/telegram.js:316:15
    at tryCatcher (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)

**Comment by rohityadav-sas** [comment]
> > > > > when and how the bot is generating the keys ?
> > > > 
> > > > 
> > > > You can create your own telegram bot using Botfather.
> > > 
> > > 
> > > i did and i send /start to the bot
> > > bot reply
> > > Welcome to the Hamster Key Generator Bot!
> > > and then errors in terminal
> > 
> > It says chat not found, You can debug that yourself.
> 
> also with another bot:
> 
> /start
> Welcome to the Hamster Key Generator Bot!
> 
> root@ins-1-s8:~/python-telegram-bot/Hamster-KeyGen# npm start
> 
> > hamster-kombat-key-generator@1.0.0 start
> > node src/app.js
> 
> Server running on port 3000
> Unhandled rejection Error: ETELEGRAM: 400 Bad Request: chat not found
>     at /root/python-telegram-bot/Hamster-KeyGen/node_modules/node-telegram-bot-api/src/telegram.js:316:15
>     at tryCatcher (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:547:31)
>     at Promise._settlePromise (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:604:18)
>     at Promise._settlePromise0 (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:649:10)
>     at Promise._settlePromises (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:729:18)
>     at _drainQueueStep (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:93:12)
>     at _drainQueue (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:86:9)
>     at Async._drainQueues (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:102:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:15:14)
>     at processImmediate (node:internal/timers:466:21)
> 
> Unhandled rejection Error: ETELEGRAM: 400 Bad Request: chat not found
>     at /root/python-telegram-bot/Hamster-KeyGen/node_modules/node-telegram-bot-api/src/telegram.js:316:15
>     at tryCatcher (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:547:31)
>     at Promise._settlePromise (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:604:18)
>     at Promise._settlePromise0 (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:649:10)
>     at Promise._settlePromises (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:729:18)
>     at _drainQueueStep (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:93:12)
>     at _drainQueue (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:86:9)
>     at Async._drainQueues (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:102:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:15:14)
>     at processImmediate (node:internal/timers:466:21)
> 
> 
> 

I just tried with a new bot. It's working totally fine.

**Comment by supmyhava** [comment]
> > > > > > when and how the bot is generating the keys ?
> > > > > 
> > > > > 
> > > > > You can create your own telegram bot using Botfather.
> > > > 
> > > > 
> > > > i did and i send /start to the bot
> > > > bot reply
> > > > Welcome to the Hamster Key Generator Bot!
> > > > and then errors in terminal
> > > 
> > > 
> > > It says chat not found, You can debug that yourself.
> > 
> > 
> > also with another bot:
> > /start
> > Welcome to the Hamster Key Generator Bot!
> > root@ins-1-s8:~/python-telegram-bot/Hamster-KeyGen# npm start
> > > hamster-kombat-key-generator@1.0.0 start
> > > node src/app.js
> > 
> > 
> > Server running on port 3000
> > Unhandled rejection Error: ETELEGRAM: 400 Bad Request: chat not found
> > at /root/python-telegram-bot/Hamster-KeyGen/node_modules/node-telegram-bot-api/src/telegram.js:316:15
> > at tryCatcher (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/util.js:16:23)
> > at Promise._settlePromiseFromHandler (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:547:31)
> > at Promise._settlePromise (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:604:18)
> > at Promise._settlePromise0 (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:649:10)
> > at Promise._settlePromises (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:729:18)
> > at _drainQueueStep (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:93:12)
> > at _drainQueue (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:86:9)
> > at Async._drainQueues (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:102:5)
> > at Immediate.Async.drainQueues [as _onImmediate] (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:15:14)
> > at processImmediate (node:internal/timers:466:21)
> > Unhandled rejection Error: ETELEGRAM: 400 Bad Request: chat not found
> > at /root/python-telegram-bot/Hamster-KeyGen/node_modules/node-telegram-bot-api/src/telegram.js:316:15
> > at tryCatcher (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/util.js:16:23)
> > at Promise._settlePromiseFromHandler (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:547:31)
> > at Promise._settlePromise (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:604:18)
> > at Promise._settlePromise0 (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:649:10)
> > at Promise._settlePromises (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:729:18)
> > at _drainQueueStep (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:93:12)
> > at _drainQueue (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:86:9)
> > at Async._drainQueues (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:102:5)
> > at Immediate.Async.drainQueues [as _onImmediate] (/root/python-telegram-bot/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:15:14)
> > at processImmediate (node:internal/timers:466:21)
> 
> I just tried with a new bot. It's working totally fine.

hmm ok so i dont know what is the problem =\
