### ISSUE TITLE
same

### ISSUE THREAD

**Issue by supmyhava** [rohityadav-sas/Hamster-KeyGen#2]
tried now on a new server and new bot same errors =\
what version of node and npm you used ?

**Comment by supmyhava** [comment]
npm start

> hamster-kombat-key-generator@1.0.0 start
> node src/app.js

(node:534942) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server running on port 3000
error: [polling_error] {}
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: chat not found
    at /root/Hamster-KeyGen/node_modules/node-telegram-bot-api/src/telegram.js:299:15
    at tryCatcher (/root/Hamster-KeyGen/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/Hamster-KeyGen/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/root/Hamster-KeyGen/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:491:21)

**Comment by rohityadav-sas** [comment]
I made some changes to the code, please try it and update if you find any other bugs

**Comment by supmyhava** [comment]
> I made some changes to the code, please try it and update if you find any other bugs

ok thats working but a lot of TooManyRegister errors
![image](https://github.com/user-attachments/assets/be471298-9d42-4e1a-af66-75395f3fb9ce)

**Comment by rohityadav-sas** [comment]
> > I made some changes to the code, please try it and update if you find any other bugs
> 
> ok thats working but a lot of TooManyRegister errors
> ![image](https://github.com/user-attachments/assets/be471298-9d42-4e1a-af66-75395f3fb9ce)
> 

That's supposed to happen. It's part of the code.

**Comment by supmyhava** [comment]
btw how to add an admin ?
also there is an option to proxy ? that can be great

**Comment by supmyhava** [comment]
> > > I made some changes to the code, please try it and update if you find any other bugs
> > 
> > 
> > ok thats working but a lot of TooManyRegister errors
> > ![image](https://private-user-images.githubusercontent.com/55424004/363518668-be471298-9d42-4e1a-af66-75395f3fb9ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMjQyMTQsIm5iZiI6MTcyNTIyMzkxNCwicGF0aCI6Ii81NTQyNDAwNC8zNjM1MTg2NjgtYmU0NzEyOTgtOWQ0Mi00ZTFhLWFmNjYtNzUzOTVmM2ZiOWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDIwNTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGEyM2JmMDYyODQwZDBjMDQ2ZTNkMzA5YzRkYTAwOGVlYjNjNDY1YjY3NWZmYjc4MzAwMGVlYzhlMzg5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p4W6BhV2_UJvxYzbj9d2qDFYp-_eNUN5h-Q2iyOQl3k)
> 
> That's supposed to happen. It's part of the code.

yeah got it

**Comment by rohityadav-sas** [comment]
> btw how to add an admin ?
> also there is an option to proxy ? that can be great

The admin part code is inside backup_admin.js You can look it yourself

For the proxy,  i will look into it.

**Comment by supmyhava** [comment]
> > btw how to add an admin ?
> > also there is an option to proxy ? that can be great
> 
> The admin part code is inside backup_admin.js You can look it yourself
> 
> For the proxy, i will look into it.

this bot is so cool mate.
2 questions if i can...
1 the keys that bot is generating is comming from my server ip right ?
2 your bot is like this one ? https://web.telegram.org/k/#@hamster_keygen_bot how this developer Is it possible to produce such an abnormal amount of keys?
Zoo - 581802
Cube - 571966
Train - 659988
Merge - 356392
Twerk - 188623
Poly - 294677
Trim - 214243
Gangs - 104023
Cafe - 383673

**Comment by rohityadav-sas** [comment]
> > > btw how to add an admin ?
> > > also there is an option to proxy ? that can be great
> > 
> > The admin part code is inside backup_admin.js You can look it yourself
> > 
> > For the proxy, i will look into it.
> 
> this bot is so cool mate.
> 2 questions if i can...
> 1 the keys that bot is generating is comming from my server ip right ?
> 2 your bot is like this one ? https://web.telegram.org/k/#@hamster_keygen_bot how this developer Is it possible to produce such an abnormal amount of keys?
> Zoo - 581802
> Cube - 571966
> Train - 659988
> Merge - 356392
> Twerk - 188623
> Poly - 294677
> Trim - 214243
> Gangs - 104023
> Cafe - 383673

Yes the key is generated using your ip address. So there is no chance of ban.

I don't know about the mass production of keys.

**Comment by supmyhava** [comment]
> I don't know about the mass production of keys.

ok my friend thank you.!
